config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'scrapper#new', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :scrapper do
    collection do
      get :download_excel
      post :delete_file
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  #Removed :registerable, :recoverable for hide "Sign up" and "Forgot Password" links on sign in page
  devise :database_authenticatable, :rememberable, :trackable, :validatable


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

	protected

	def after_sign_in_path_for(resource)
		new_scrapper_path
	end
end

app/controllers/scrapper_controller.rb
require 'nokogiri'
require 'open-uri'

class ScrapperController < ApplicationController
	before_action :authenticate_user!
	def new
	end

	def create
		if params[:url].present?
			begin
				@profile = Linkedin::Profile.new(params[:url], { company_details: true, proxy_ip: '127.0.0.1', proxy_port: '3128', username: 'demo dev', password: 'demo@123' })
			rescue Exception => e
				puts "======>message start"
				logger.error e.message
				puts "======>message end"
				flash[:notice] = "Profile not found. Please try with different profile URL"
				redirect_to new_scrapper_path	
			end
			if @profile.present?
				header = "PROSPECT CODE, MINING DATE, CALLING DATE, DOMAIN, INDUSTRY SEGMENT, FUNCTIONS, FIRST NAME, LAST NAME, DESIGNATION, ORGANIZATION, EMAIL, WORK PHONE, WEBSITE, CITY, STATE, COUNTRY, PERSONAL WEBSITE"
				dir = Dir.mkdir("#{Rails.root}/profiles") unless Dir.exists?("#{Rails.root}/profiles")
				file = File.new("#{Rails.root}/profiles/linkedin-profiles.csv", "a") 
				unless File.exist?(File.dirname(file))
				  FileUtils.mkdir_p(File.dirname(file))
				end
				city_state_country = Nokogiri::HTML(open(params[:url])).at_css(".locality").text.split(",")
		    File.open(file, "a:UTF-16LE:UTF-8") do |csv|
		    	file_last_line = IO.readlines("#{Rails.root}/profiles/linkedin-profiles.csv", "a")
		    	csv << header unless file_last_line.first.present?
		    	csv.write "\n"
		    	csv << ","
		    	csv << Time.now.strftime("%d/%^b/%Y")
		    	csv << ","
		    	csv << ","
		    	csv << ","
		    	csv << ","
		    	csv << ","
		    	csv << @profile.first_name
		    	csv << ","
		    	csv << @profile.last_name
		    	csv << ","
		    	csv << @profile.current_companies.first[:title]
		    	csv << ","
		    	csv << @profile.current_companies.first[:company]
		    	csv << ","
		    	csv << ","
		    	csv << ","
		    	csv << ","
		    	csv << @profile.location rescue nil
		    	csv << ","
		    	csv << city_state_country[1] rescue nil
		    	csv << ","
		    	csv << @profile.country rescue nil
		    	csv << ","
		    	csv << @profile.linkedin_url rescue nil
		    end
		    flash[:success] = "Profile details has been added successfully"
		  	redirect_to new_scrapper_path
			end
		end
	end

	def download_excel
		send_file "#{Rails.root}/profiles/linkedin-profiles.csv", :type => 'application/vnd.ms-excel; charset=utf-8'
	end

	def delete_file
		if FileUtils.rm_rf("#{Rails.root}/profiles")
			flash[:success] = 'File deleted successfully'
		else
			flash[:notice] = 'File not deleted. Please try again.'
		end
		redirect_to new_scrapper_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scrapper_helper.rb
module ScrapperHelper
end

app/views/layouts/_flash_notice.html.erb
<%- flash.each do |name, message| %>
	<% if name == "success" %>
  	<div style='color:white;background-color:green;'><%= message %></div>
  <% elsif name == "notice" %>
    <div style='color:white;background-color:red;'><%= message %></div>
  <% end %>
<%- end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LinkedinScrapper</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/flash_notice' %>
<%= yield %>

</body>
</html>

app/views/scrapper/new.html.erb
<br/><br/>
<div style="width:500px;">
	<%= form_tag  scrapper_index_path, method: :post  do |f| %>
	  <label>Enter Profile URL: </label>
	  <%= text_field_tag "url", "", style: 'width:490px;' %>
	  <%= submit_tag "Save" %>
	<% end %>

	<%- if File.exist?("#{Rails.root}/profiles/linkedin-profiles.csv") && current_user.present? %>
		<%= link_to "Download", download_excel_scrapper_index_path, style: 'float:right;padding-top:-10px !important;' %>
		<br/><br/>
		<%= link_to "Delete File", delete_file_scrapper_index_path, data: { confirm: 'Are you sure you want to delete this file?' }, method: :post, style: 'float:right;padding-top:-10px !important;' %>
	<%- end %>

	<%- if current_user.present? %>
		</br></br>
		<%= link_to "Sign Out", destroy_user_session_path, method: :delete, style: 'float:right' %>
	<%- end %>
</div>